# Generated by Django 4.2.30 on 2026-09-05 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('course_code', models.CharField(blank=True, max_length=50, verbose_name='Mã học phần / Tên môn')),
                ('faculty', models.CharField(blank=True, max_length=100, verbose_name='Khoa / Ngành')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá bán (VNĐ)')),
                ('is_free', models.BooleanField(default=False, verbose_name='Tặng miễn phí (0đ)')),
                ('condition', models.CharField(choices=[('NEW', 'Mới (100%)'), ('LIKE_NEW', 'Như mới (90-99%)'), ('GOOD', 'Tốt (70-89%)'), ('USED', 'Cũ (Dưới 70%)')], default='GOOD', max_length=20, verbose_name='Tình trạng')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('image_url', models.URLField(default='https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80', verbose_name='Link ảnh sản phẩm')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Đã bán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.category', verbose_name='Danh mục')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(blank=True, related_name='favorite_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_main.post')),
            ],
        ),
    ]
